; Listing generated by Microsoft (R) Optimizing Compiler Version 19.15.26729.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\Minh Tran\AppData\Local\Temp\.NETFramework,Version=v4.7.1.AssemblyAttributes.cpp"
